=== ext/slideshow/frontend/settings.dtd
<!ELEMENT settings (group*)>

<!ELEMENT group   (description?, item+)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT item  (#PCDATA)>

<!ATTLIST group 	name ID #REQUIRED>
<!ATTLIST item 		name ID #REQUIRED
					title CDATA #IMPLIED
					type (string|int|float|directory|file|resolution|password) #REQUIRED
					description CDATA #IMPLIED
					install (yes|no) "no">

=== ext/slideshow/frontend/settings.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE settings SYSTEM "settings.dtd">
<settings>
	<group name="Path">
		<description>The basepath is the homedirectory of the frontend. All other paths are relative to it.</description>
		
		<item name="BasePath" type="directory" description="foo bar baz"></item>
		<item name="Image" type="directory">image</item>
		<item name="Video" type="directory">video</item>
		<item name="Temp" type="directory">tmp</item>
	</group>
	
	<group name="Files">
		<description>All file paths are either relative to BasePath or an absolute path.</description>
		
		<item name="BinaryPath" type="file"></item>
		<item name="BaseLog" type="file">slideshow.log</item>
		<item name="ActivityLog" type="file">activity.log</item>
		<item name="PID" type="file">slideshow.pid</item>
		<item name="MOTD" type="file">motd</item>
		<item name="convert" type="file"></item>
	</group>
	
	<group name="Apparence">
		<description>Visual apperance.</description>
		
		<item name="Background" type="file" description="Background image used when creating text slides"></item>
		<item name="Font" type="file" description="Font used when creating text slides"></item>
		<item name="Resolution" type="resolution" description="Resolution of the daemon">800x600</item>
		<item name="VirtualResolution" title="Virtual resolution" type="resolution" description="If the display forces another resolution (e.g some widescreen projectors) set this to that resolution"></item>
		<item name="TransitionTime" type="float" description="Time in sec it takes to change slide">3.0</item>
		<item name="SwitchTime" type="float" description="Time in sec each slide will be shown">10.0</item>
	</group>
	
	<group name="Database">
		<description>Database settings. Leave the password blank unless you need to change it.</description>
		
		<item name="Username" type="string"></item>
		<item name="Password" type="password"></item>
		<item name="Hostname" type="string">localhost</item>
		<item name="Name" type="string"></item>
	</group>
	
	<group name="Slideshow">
		<description>Bajs</description>
		
		<item name="Title" type="string" description="Webgui title">Slideshow</item>
	</group>
</settings>

=== ext/slideshow/slideshow/settings.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE settings SYSTEM "settings.dtd">
<settings>
	<group name="Path">
		<description>The base directory is the homedirectory of the frontend. All other paths are relative to it.</description>
		
		<item name="BasePath" title="Base directory" type="directory">{CWD}</item>
		<item name="Image" type="directory" rel="Path.BasePath">image</item>
		<item name="Video" type="directory" rel="Path.BasePath">video</item>
		<item name="Temp" type="directory" rel="Path.BasePath">tmp</item>
	</group>
	
	<group name="Files">
		<description>All file paths are either relative to BasePath or an absolute path.</description>
		
		<item name="BinaryPath" title="Exectuable path" description="Path where slideshow binaries exist." type="file">slideshow-daemon</item>
		<item name="BaseLog" title="Logfile" type="file">slideshow.log</item>
		<item name="ActivityLog" title="Activity logfile" type="file">activity.log</item>
		<item name="PID" type="file"  rel="Path.BasePath">slideshow.pid</item>
		<item name="MOTD" type="file"  rel="Path.BasePath" description="Message of the day">motd</item>
		<item name="convert" title="ImageMagick convert" type="file" description="ImageMagick is used to scale and convert the slides">/usr/bin/convert</item>
	</group>
	
	<group name="Appearance">
		<description>
			The resolution is best left unset, which means to use the currently
			used by X, which is preferably set to match the native resolution of
			the display. In general, what is important is the aspect ratio but
			using the native resolution for X and slideshow ensures that pixels
			aren't scaled in any way.<br/>
			<br/>
			If the display forces another resolution or aspect ratio than X uses
			(e.g some widescreen projectors) set the virtual resolution to the
			resolution used by the display and the regular resolution to the
			resolution used by X. However, be careful using virtual resolution
			as the slides will be stretched. It is suggested to use a resolution
			which matches either dimension and is an as close match as possible.
		</description>

		<item name="Resolution" type="resolution" description="Display resolution" allow_empty="1">1280x1024</item>
		<item name="VirtualResolution" title="Virtual resolution" type="resolution" description="Window resolution" allow_empty="1"></item>
		<item name="Theme" title="Theme" type="file" description="Theme for text-based slides">default.xml</item>
		<item name="TransitionTime" title="Transition time" type="float" description="Time in sec it takes to change slide">3.0</item>
		<item name="SwitchTime" title="Switch time" type="float" description="Time in sec each slide will be shown">10.0</item>
		<item name="Display" title="Display" type="display" description="X display to use">:0.0</item>
	</group>
	
	<group name="Database">
		<description>Database settings. Leave the password blank unless you need to change it.</description>

		<item name="String" title="" type="static"></item>
		<item name="Provider" type="string">sqlite3</item>
		<item name="Username" type="string"></item>
		<item name="Password" type="password"></item>
		<item name="Hostname" type="string"></item>
		<item name="Name" type="string">site.db</item>
	</group>
	
	<group name="Slideshow">
		<description>These settings only affects the webGUI.</description>
		
		<item name="Title" type="string" description="WebGUI title">Slideshow</item>
	</group>
	
	<group name="Runtime" hidden="1">
		<description>This is settings just for storage, like which current queue is run (so it will persist between runs)</description>
		<item name="queue" type="integer">1</item>
	</group>

	<group name="cherrypy" hidden="1" ignore="1">
		<description>Cherrypy settings</description>
	</group>
</settings>
